### ISSUE TITLE
Command example?

### ISSUE THREAD

**Issue by MaltySalty** [rreminy/FFXIV.WinTitle#4]
I've been tryin to use this plugin to change the title screen but

/wintitle Heavensward 

or 

/wintitle Shadowbringers 

doesn't seem to work? I press the command and then log out back to the main screen and nothing got changed? Did I do something wrong?

**Comment by Sebdevar** [comment]
Hey, so I know it's not easy to tell from the lacking readme, but this doesn't change the title screen but the applications title (you know, the name that shows up when you hover it in your taskbar and what shows up in the process manager).

Go check [Title Edit](https://github.com/lmcintyre/TitleEditPlugin) instead, it does what you're looking for ;).

**Comment by rreminy** [comment]
I should probably place a screenshot, apologies I didn't catch this before

**Comment by rreminy** [comment]
This has been resolved: https://github.com/goatcorp/DalamudPluginsD17/pull/1493
